# Generated by Django 4.1 on 2022-09-07 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postCreate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extenduser',
            name='email',
            field=models.EmailField(max_length=50, verbose_name='email'),
        ),
    ]
